#include "pidfile.h"
#include "server.h"
#include "strlcpy.h"
#include "table.h"
#include "utils.h"
#include "conf/conf.h"
#include  "conf/proxyc.h"
#include "conf/proxycc.h"
#include "conf/proxyce.h"
#include "conf/proxycp.h"
#include "conf/proxycs.h"
#define MAX_CONNECTION 100
